### ISSUE TITLE
Make scallop conf serializable?

### ISSUE THREAD

**Issue by vsuthichai** [scallop/scallop#137]
Would it be possible to make ScallopConf and any of its members serializable?  My use case is that I use scallop as an argument parser within a Spark job.  When it becomes necessary to serialize across the cluster, this part fails.  I can of course copy argument values out of the configuration object first, but this part can become tedious if there are several things that need to be copied.

**Comment by Rogach** [comment]
Yes, it should be possible. I'll do it, but I'm currently very short on time and will probably only get to it on the next week.

**Comment by zie1ony** [comment]
Is it in progress?

**Comment by Rogach** [comment]
@zie1ony Yes, I hope to finally get around to it this week.

**Comment by Rogach** [comment]
I tried making ScallopConf and all other classes serializable, but it didn't really work - there is a lot of magic with classloaders and scala collections, and it results in horrible failures when deserializing.

However, I managed to implement custom serialization using Serialization Proxy Pattern - exploiting the fact that ScallopConf should always arrive at the same state when provided with same arguments. Here's the [example code](https://github.com/scallop/scallop/blob/7db98b9dd2657bd62270e01fc7c581a8aee2f807/jvm/src/test/scala/SerializationTest.scala).

Essentially, this only serializes `Array[String]` of arguments and re-creates original configuration on deserialization.

Will such solution work for you?

@vsuthichai @zie1ony

**Comment by bzz** [comment]
I believe the motivation to make it Serializable was to able to access it inside closures, which are subject of [closure cleaning](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/ClosureCleaner.scala#L152) and [serialization](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/serializer/JavaSerializer.scala) procedures in Apache Spark.

```scala
$ spark-shell --master "local[*]" --packages org.rogach:scallop_2.11:3.0.3

import org.rogach.scallop._

val args = Array("--apples", "33")
class Conf(arguments: Seq[String]) extends org.rogach.scallop.ScallopConf(arguments) {
  val apples = opt[Int](required = true)
  verify()
}

val conf = new Conf(args)
sc.parallelize(Seq(1,2,3)).map { i =>
  println(s"$i: " + conf.apples() + " apples")
}
```

Which right now results in `org.apache.spark.SparkException: Task not serializable` below
<details>

```
org.apache.spark.SparkException: Task not serializable
  at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:298)
  at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:288)
  at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
  at org.apache.spark.SparkContext.clean(SparkContext.scala:2287)
  at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:370)
  at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:369)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.map(RDD.scala:369)
  ... 52 elided
Caused by: java.io.NotSerializableException: Conf
Serialization stack:
	- object not serializable (class: Conf, value: Conf@905e189)
	- field (class: $iw, name: conf, type: class Conf)
```
</details>

Sorry if I misunderstood something, but it's not immediately clear how to apply suggested workaround in this situation.

Thanks for the great library, and it would be nice to get it working for Apache Spark jobs without explicitly coping each argument!

**Comment by Rogach** [comment]
@bzz Can you try it with the following example code? (I applied the workaround to your example, but don't have spark shell around)
https://gist.github.com/Rogach/e401f0c6111cd15fcf3c907813dcd7b8

**Comment by bzz** [comment]
Thank you @Rogach for both, prompt response and an expository example!
That works like a charm. 

Do you think it will be possible to include it as part of scallop release, or does every Spark app have to define such proxy?

**Comment by Rogach** [comment]
@bzz I will include it in the next release, but since I can't access instance constructor from a trait, some manual plumbing will be needed when creating the configuration. I'm thinking to make something like the following:

```scala
class Conf(args: Seq[String]) extends ScallopConf(args) with SerializationProxy {
  val apples = opt[Int](required = true)
  verify()

  def deserialize(args: Seq[String]) = new Conf(args)
}
```

**Comment by bzz** [comment]
👍 that looks really nice.

I extra line for case of Apache Spark application sounds great. 
Thank you very much for fast turnaround!

**Comment by Rogach** [comment]
I managed to create a simple mixin, that brings the whole work to get serialization down to:
```scala
class Conf(args: Seq[String]) extends ScallopConf with Serialization {
  // the usual option definitions
}
```
However, the implementation requires quite a lot of scary stuff - it uses reflection to get class constructor, and expects class constructor to have only one parameter for the args (Seq[String] or List[String]). (you can see the mixin code [here](https://github.com/scallop/scallop/blob/develop/jvm/src/main/scala/org.rogach.scallop/SerializationProxy.scala)).

I could include this mixin on ScallopConf by default, but due to this fragile implementation I don't want to - I think the user should at least read a warning in scaladoc before using it.

I released the change in `3.1.0`, would be great if you could test it!

**Comment by alex-g-belov** [comment]
Hello. I'm still seeing a serialization issue when passing in props. The exception I see is:

org.apache.spark.SparkException: Task not serializable
...

Caused by: java.io.NotSerializableException: org.rogach.scallop.LazyMap
Serialization stack:
        - object not serializable (class: org.rogach.scallop.LazyMap, value: Map())

**Comment by Rogach** [comment]
@alex-g-belov Can you please provide Scallop, Scala and JVM versions used? I currently failed to reproduce the issue on my setup.

**Comment by alex-g-belov** [comment]
Scallop: 3.1.2
Scala: 2.11
Java: Java 8

I use Scallop multiple times in my package, and the only time that its showing the serialization errors is when its called from within Spark's Dataset.foreachPartition call: 
https://spark.apache.org/docs/2.2.0/api/java/org/apache/spark/sql/Dataset.html#foreachPartition-org.apache.spark.api.java.function.ForeachPartitionFunction-

So I suspect the problem might be with Spark, not Scallop.

**Comment by Rogach** [comment]
Still can't reproduce (tried different `2.11.x` Scala versions). My test case: https://gist.github.com/Rogach/41a7331047026d7d392ec1581f4b620a

Maybe you hit this bug? https://issues.scala-lang.org/browse/SI-7005

Can you please show the full `ScallopConf` code that triggers the error (or at least the `props` call that triggers an error)? Maybe you do something with the map that is returned from `props()` call?

**Comment by alex-g-belov** [comment]
I am passing in this argument as a trait:

```
import org.rogach.scallop.ScallopConf

trait OverwriteSparkConfigurationArgument extends ScallopConf {
  @transient val overrideSparkConfigMap: Map[String, String] = props[String]('O',
    descr = "override zero or more spark configurations by specifying '-Okey=value' for each configuration")
}

```

The base class is 

`class AppArguments(arguments: Array[String]) extends ScallopConf(arguments) with Serialization with DomainArgument with OverwriteSparkConfigurationArgument with Loggable {
`

and it is being called here: 

`abstract class Application(val appArgs: AppArguments) extends Loggable with SparkSessionComponent with RequiredDomainContext with OverrideSparkConfiguration with Serializable {
  override val domain: String = appArgs.domain()
  override val overrideSparkConfigMap: Map[String, String] = appArgs.overrideSparkConfigMap
...

`
Which is then passed in here:

` 
  def defaultSparkSession(appName: String, overrideSparkConfigMap: Map[String, String] = Map()): SparkSession = {
    val conf: SparkConf = defaultSparkConf(appName)
    overrideSparkConfigMap.foreach {
      case (key, value) => conf.set(key, value)
    }
    defaultSparkSession(conf)
  }
`

**Comment by Rogach** [comment]
@alex-g-belov - Good news, I managed to reproduce the bug with the following test case: https://gist.github.com/Rogach/41a7331047026d7d392ec1581f4b620a

I'll now try to understand the cause of the issue.

**Comment by Rogach** [comment]
Here's a simple fix that fixes my test case:
```
override val overrideMap: Map[String, String] = appArgs.overrideMap.map(identity)
```

The problem is that LazyMap encapsulates a lazy reference to another map inside Scallop state, and thus can't be serialized properly. ScallopConf avoids that problem entirely by serializing only arguments array and recreating the entire configuration when deserializing, thus it does not have to serialize the internal state.

**Comment by alex-g-belov** [comment]
Great, thank you so much for your help!
